// Generated by gencpp from file extractor/map.msg
// DO NOT EDIT!


#ifndef EXTRACTOR_MESSAGE_MAP_H
#define EXTRACTOR_MESSAGE_MAP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <extractor/feature.h>
#include <geometry_msgs/Pose.h>

namespace extractor
{
template <class ContainerAllocator>
struct map_
{
  typedef map_<ContainerAllocator> Type;

  map_()
    : header()
    , features()
    , robotposition()  {
    }
  map_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , features(_alloc)
    , robotposition(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::extractor::feature_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::extractor::feature_<ContainerAllocator> >::other >  _features_type;
  _features_type features;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _robotposition_type;
  _robotposition_type robotposition;




  typedef boost::shared_ptr< ::extractor::map_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::extractor::map_<ContainerAllocator> const> ConstPtr;

}; // struct map_

typedef ::extractor::map_<std::allocator<void> > map;

typedef boost::shared_ptr< ::extractor::map > mapPtr;
typedef boost::shared_ptr< ::extractor::map const> mapConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::extractor::map_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::extractor::map_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace extractor

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'extractor': ['/home/kevin/Documents/catkin_ws/src/extractor/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::extractor::map_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::extractor::map_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::extractor::map_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::extractor::map_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::extractor::map_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::extractor::map_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::extractor::map_<ContainerAllocator> >
{
  static const char* value()
  {
    return "605ba2556bdcd481e241a16199e3f3a4";
  }

  static const char* value(const ::extractor::map_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x605ba2556bdcd481ULL;
  static const uint64_t static_value2 = 0xe241a16199e3f3a4ULL;
};

template<class ContainerAllocator>
struct DataType< ::extractor::map_<ContainerAllocator> >
{
  static const char* value()
  {
    return "extractor/map";
  }

  static const char* value(const ::extractor::map_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::extractor::map_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
feature[] features\n\
geometry_msgs/Pose robotposition\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: extractor/feature\n\
Header header\n\
geometry_msgs/Point position\n\
float64 diameter\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::extractor::map_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::extractor::map_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.features);
      stream.next(m.robotposition);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct map_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::extractor::map_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::extractor::map_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "features[]" << std::endl;
    for (size_t i = 0; i < v.features.size(); ++i)
    {
      s << indent << "  features[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::extractor::feature_<ContainerAllocator> >::stream(s, indent + "    ", v.features[i]);
    }
    s << indent << "robotposition: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.robotposition);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXTRACTOR_MESSAGE_MAP_H
